"""empty message

Revision ID: 15e1a3c37c67
Revises: 
Create Date: 2024-01-22 00:47:47.537771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15e1a3c37c67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('first_name', sa.String(length=200), nullable=False),
    sa.Column('last_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('new_password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=200), nullable=False),
    sa.Column('last_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('bank_account', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=200), nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('contact', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holidaycalendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('holiday_name', sa.String(), nullable=False),
    sa.Column('company_eventID', sa.Integer(), nullable=False),
    sa.Column('company_event_description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'company_eventID')
    )
    op.create_table('leavetype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leave_description', sa.String(), nullable=False),
    sa.Column('leave_days', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('leave_balances', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_ID', sa.Integer(), nullable=True),
    sa.Column('clock_in', sa.DateTime(), nullable=True),
    sa.Column('clock_out', sa.DateTime(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['employee_ID'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('communication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_ID', sa.Integer(), nullable=True),
    sa.Column('employee_ID', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['admin_ID'], ['admin.id'], ),
    sa.ForeignKeyConstraint(['employee_ID'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee__leaverequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leavetype_ID', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('admin_comment', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('Return_date', sa.Date(), nullable=False),
    sa.Column('leave_balances', sa.Float(), nullable=True),
    sa.Column('employee_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_ID'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['leavetype_ID'], ['leavetype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_ID', sa.Integer(), nullable=True),
    sa.Column('employee_ID', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['admin_ID'], ['admin.id'], ),
    sa.ForeignKeyConstraint(['employee_ID'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payroll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_ID', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('gross', sa.Float(), nullable=False),
    sa.Column('allowances', sa.Float(), nullable=True),
    sa.Column('deductions', sa.Float(), nullable=True),
    sa.Column('bonuses', sa.Float(), nullable=True),
    sa.Column('taxes', sa.Float(), nullable=True),
    sa.Column('net', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['employee_ID'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payroll')
    op.drop_table('notification')
    op.drop_table('employee__leaverequest')
    op.drop_table('communication')
    op.drop_table('attendance')
    op.drop_table('user')
    op.drop_table('leavetype')
    op.drop_table('holidaycalendar')
    op.drop_table('employee')
    op.drop_table('admin')
    # ### end Alembic commands ###
