"""empty message

Revision ID: 3c26e90d0a89
Revises: 
Create Date: 2024-02-05 20:44:25.399317

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c26e90d0a89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('employee_ID', sa.Integer(), nullable=True))
    op.add_column('attendance', sa.Column('clock_in', sa.DateTime(), nullable=True))
    op.add_column('attendance', sa.Column('clock_out', sa.DateTime(), nullable=True))
    op.add_column('attendance', sa.Column('date', sa.Date(), nullable=False))
    op.drop_constraint('attendance_employee_id_fkey', 'attendance', type_='foreignkey')
    op.create_foreign_key(None, 'attendance', 'employee', ['employee_ID'], ['id'])
    op.drop_column('attendance', 'employee_id')
    op.drop_column('attendance', 'clock_in_time')
    op.drop_column('attendance', 'clock_out_time')
    op.add_column('communication', sa.Column('admin_ID', sa.Integer(), nullable=True))
    op.add_column('communication', sa.Column('employee_ID', sa.Integer(), nullable=True))
    op.alter_column('communication', 'message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('communication_sender_id_fkey', 'communication', type_='foreignkey')
    op.drop_constraint('communication_receiver_id_fkey', 'communication', type_='foreignkey')
    op.create_foreign_key(None, 'communication', 'employee', ['employee_ID'], ['id'])
    op.create_foreign_key(None, 'communication', 'admin', ['admin_ID'], ['id'])
    op.drop_column('communication', 'receiver_id')
    op.drop_column('communication', 'sender_id')
    op.alter_column('employee', 'bank_account',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('employee', 'contact',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.drop_column('holidaycalendar', 'company_event_description')
    op.drop_column('holidaycalendar', 'company_eventID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holidaycalendar', sa.Column('company_eventID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('holidaycalendar', sa.Column('company_event_description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('employee', 'contact',
               existing_type=sa.String(length=15),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('employee', 'bank_account',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.add_column('communication', sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('communication', sa.Column('receiver_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'communication', type_='foreignkey')
    op.drop_constraint(None, 'communication', type_='foreignkey')
    op.create_foreign_key('communication_receiver_id_fkey', 'communication', 'user', ['receiver_id'], ['id'])
    op.create_foreign_key('communication_sender_id_fkey', 'communication', 'user', ['sender_id'], ['id'])
    op.alter_column('communication', 'message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('communication', 'employee_ID')
    op.drop_column('communication', 'admin_ID')
    op.add_column('attendance', sa.Column('clock_out_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('attendance', sa.Column('clock_in_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('attendance', sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.create_foreign_key('attendance_employee_id_fkey', 'attendance', 'employee', ['employee_id'], ['id'])
    op.drop_column('attendance', 'date')
    op.drop_column('attendance', 'clock_out')
    op.drop_column('attendance', 'clock_in')
    op.drop_column('attendance', 'employee_ID')
    # ### end Alembic commands ###
