"""empty message

Revision ID: 694884c653ad
Revises: 15e1a3c37c67
Create Date: 2024-01-22 00:48:26.449133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '694884c653ad'
down_revision = '15e1a3c37c67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('new_password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_password', sa.VARCHAR(length=200), nullable=False))

    # ### end Alembic commands ###
