"""Back to normal

Revision ID: b34d6d3169d8
Revises: c943ce73cc32
Create Date: 2024-01-21 03:44:53.251025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b34d6d3169d8'
down_revision = 'c943ce73cc32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leavetype', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leave_description', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leavetype', schema=None) as batch_op:
        batch_op.drop_column('leave_description')

    # ### end Alembic commands ###
