"""Created employee leave balances

Revision ID: e0eef111bb1c
Revises: 
Create Date: 2024-02-11 23:23:58.716744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0eef111bb1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_balances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('annual_leave', sa.Integer(), nullable=False),
    sa.Column('annual_leave_entitled', sa.Integer(), nullable=True),
    sa.Column('study_leave', sa.Integer(), nullable=False),
    sa.Column('study_leave_entitled', sa.Integer(), nullable=False),
    sa.Column('sick_leave', sa.Integer(), nullable=False),
    sa.Column('maternity_leave', sa.Integer(), nullable=False),
    sa.Column('maternity_leave_entitled', sa.Integer(), nullable=False),
    sa.Column('pertenity_leave', sa.Integer(), nullable=False),
    sa.Column('pertenity_leave_entitled', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    with op.batch_alter_table('holidaycalendar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_eventID', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('company_event_description', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holidaycalendar', schema=None) as batch_op:
        batch_op.drop_column('company_event_description')
        batch_op.drop_column('company_eventID')

    op.drop_table('employee_balances')
    # ### end Alembic commands ###
